[package]
name = "pi_quadrature_rust"
version = "1.0.0"
authors = ["Russel Winder <russel@winder.org.uk>"]
edition = "2018"

[lib]
name = "output"
path = "src/output.rs"
crate-type = ["rlib"]

[dependencies]
time = "*"
num_cpus = "*"
rayon = "*"
