[package]
name = "Ï€ by Quadrature in Rust"
version = "1.0.0"
authors = ["Russel Winder <russel@winder.org.uk>"]

[lib]
name = "output"
path = "src/output.rs"
crate-type = ["rlib"]

[dependencies]
time = "*"
num_cpus = "*"
rayon = "*"
